name: Publisher Workflow

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4   
      with:
        dotnet-version: 8.0.x
    
    - name: Restore Dependencies
      run: dotnet restore

    - id: build
      name: Build      
      run: dotnet build --no-restore

    - name: Run MSTests
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

    - name: Upload Test Results
      if: always() # Ensures results are uploaded even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: mstest-results
        path: "**/TestResults/*.trx"